apiVersion: v1
kind: Service
metadata:
  name: inferno-fhir-validator
  namespace: ${namespace}
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    workload: inferno-fhir-validator
