apiVersion: apps/v1
kind: Deployment
metadata:
  name: inferno-app
  namespace: ${namespace}
spec:
  replicas: 1
  selector:
    matchLabels:
      workload: inferno-app
  template:
    metadata:
      labels:
        workload: inferno-app
    spec:
      initContainers:
      - name: run-migrations
        image: ${inferno_image}
        imagePullPolicy: Always
        command: ["bundle", "exec", "rake", "db:migrate"]
        env:
        - name: REDIS_URL
          value: redis://inferno-redis:6379
        - name: RAILS_ENV
          value: production
        envFrom:
        - secretRef:
            name: postgres-database
        - configMapRef:
            name: postgres
      containers:
      - name: inferno-app
        image: ${inferno_image}
        imagePullPolicy: Always
        ports:
          - containerPort: 4567
        env:
        - name: REDIS_URL
          value: redis://inferno-redis:6379
        - name: RAILS_ENV
          value: production
        envFrom:
        - secretRef:
            name: postgres-database
        - configMapRef:
            name: postgres
