apiVersion: apps/v1
kind: Deployment
metadata:
  name: inferno-app
  namespace: ${namespace}
spec:
  replicas: 1
  selector:
    matchLabels:
      workload: inferno-app
  template:
    metadata:
      labels:
        workload: inferno-app
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      initContainers:
      - name: run-migrations
        image: ${inferno_image}
        imagePullPolicy: Always
        command: ["bundle", "exec", "rake", "db:migrate"]
        envFrom:
        - secretRef:
            name: postgres-database
        - configMapRef:
            name: postgres
        - configMapRef:
            name: inferno
      containers:
      - name: inferno-app
        image: ${inferno_image}
        imagePullPolicy: Always
        ports:
          - containerPort: 4567
        envFrom:
        - secretRef:
            name: postgres-database
        - configMapRef:
            name: postgres
        - configMapRef:
            name: inferno
 
