apiVersion: v1
kind: Service
metadata:
  name: inferno-postgres
  namespace: ${namespace}
spec:
  type: NodePort
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    workload: inferno-postgres
