apiVersion: v1
kind: Service
metadata:
  name: validator-web-proxy
  namespace: ${namespace}
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    workload: validator-web-proxy
