apiVersion: v1
kind: Service
metadata:
  name: validator-web
  namespace: ${namespace}
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    workload: validator-web
