apiVersion: apps/v1
kind: Deployment
metadata:
  name: validator-web
  namespace: ${namespace}
spec:
  replicas: 1
  selector:
    matchLabels:
      workload: validator-web
  template:
    metadata:
      labels:
        workload: validator-web
    spec:
      containers:
      - name: validator-web
        image: infernocommunity/fhir-validator-app:latest
        imagePullPolicy: Always
        env:
        - name: EXTERNAL_VALIDATOR_URL
          value: ${external_validator_url}
        - name: VALIDATOR_BASE_PATH
          value: ${validator_base_path}
        ports:
        - containerPort: 80
