apiVersion: v1
kind: Service
metadata:
  name: validator-api
  namespace: ${namespace}
spec:
  type: NodePort
  ports:
    - port: 3500
      protocol: TCP
      targetPort: 3500
  selector:
    workload: validator-api
