apiVersion: v1
kind: Service
metadata:
  name: validator_service
  namespace: ${namespace}
spec:
  type: NodePort
  ports:
    - port: 4567
      protocol: TCP
      targetPort: 4567
  selector:
    workload: inferno-validator
