apiVersion: apps/v1
kind: Deployment
metadata:
  name: validator-api
  namespace: ${namespace}
spec:
  replicas: 1
  selector:
    matchLabels:
      workload: validator-api
  template:
    metadata:
      labels:
        workload: validator-api
    spec:
      volumes:
      - name: igs
        emptyDir:
          sizeLimit: "10M"
      initContainers:
      - name: copy-ig
        image: ${inferno_image}
        imagePullPolicy: Always
        command: ["cp", "/opt/inferno/lib/au_core_test_kit/igs/hl7.fhir.au.core#0.3.0-ballot.tgz", "/home/igs"]
        volumeMounts:
        - name: igs
          mountPath: /home/igs
      containers:
      - name: validator-api
        image: infernocommunity/fhir-validator-service:latest
        imagePullPolicy: Always
        env:
        - name: TX_SERVER_URL
          value: ${terminology_server}
        ports:
        - containerPort: 4567
        volumeMounts:
        - name: igs
          mountPath: /home/igs
          readOnly: true
