AllCops:
  Exclude:
    - 'worker.rb'
    - 'spec/au_core/search_test_spec.rb'
    - 'lib/au_core_test_kit/search_test.rb'
    - 'lib/au_core_test_kit/search_test_properties.rb'
    - 'spec/spec_helper.rb'
    - 'spec/au_core/provenance_validator_spec.rb'
    - 'spec/au_core/must_support_test_spec.rb'
    - 'spec/au_core/generator/must_support_metadata_extractor_spec.rb'
    - 'spec/au_core/date_search_validation_test_spec.rb'
    - 'lib/au_core_test_kit/validation_test.rb'
    - 'lib/au_core_test_kit/request_logger.rb'
    - 'lib/au_core_test_kit/reference_resolution_test.rb'
    - 'lib/au_core_test_kit/read_test.rb'
    - 'lib/au_core_test_kit/provenance_validator.rb'
    - 'lib/au_core_test_kit/must_support_test.rb'
    - 'lib/au_core_test_kit/helpers.rb'
    - 'lib/au_core_test_kit/generator/value_extractor.rb'
    - 'lib/au_core_test_kit/generator/validation_test_generator.rb'
    - 'lib/au_core_test_kit/generator/terminology_binding_metadata_extractor.rb'
    - 'lib/au_core_test_kit/generator/summary_generator.rb'
    - 'lib/au_core_test_kit/generated/**/*'
    - 'lib/au_core_test_kit/generator/search_test_generator.rb'
    - 'lib/au_core_test_kit/generator/search_metadata_extractor.rb'
    - 'lib/au_core_test_kit/generator/search_definition_metadata_extractor.rb'
    - 'lib/au_core_test_kit/generator/must_support_test_generator.rb'
    - 'lib/au_core_test_kit/custom_groups/**/*'
    - 'lib/au_core_test_kit/date_search_validation.rb'
    - 'lib/au_core_test_kit/fhir_resource_navigation.rb'
    - 'lib/au_core_test_kit/generator/provenance_revinclude_search_test_generator.rb'
    - 'lib/au_core_test_kit/generator/must_support_metadata_extractor_au_core_3.rb'
    - 'lib/au_core_test_kit/generator/must_support_metadata_extractor.rb'
    - 'lib/au_core_test_kit/generator/ig_resources.rb'
    - 'lib/au_core_test_kit/generator/ig_metadata_extractor.rb'
    - 'lib/au_core_test_kit/generator/ig_loader.rb'
    - 'lib/au_core_test_kit/generator/group_metadata_extractor.rb'
    - 'lib/au_core_test_kit/generator/group_generator.rb'
    - 'lib/au_core_test_kit/generator/group_metadata.rb'
    - 'lib/au_core_test_kit/generator.rb'
Style/Documentation:
  Enabled: false
