name: test
on: push
jobs:
    Spec:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0
            - name: Run tests
              run: make tests
